name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'aymeric-dispa'
          reponame: 'hermeton-sur-miel'
          token: ${{ secrets.GITHUB_TOKEN }}
          cname: 'hermeton-sur-miel.be'